CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS role (
  rid SERIAL PRIMARY KEY,
  rname VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS app_user (
  uid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(30),
  rid INTEGER NOT NULL REFERENCES role(rid),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO role (rname)
VALUES ('CUSTOMER'), ('ADMIN'), ('SHIPMENT_STAFF')
ON CONFLICT (rname) DO NOTHING;
